/*
 * Copyright (c) 2025, Alif Semiconductor. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <arch.h>
#include <asm_macros.S>
#include <platform_def.h>

	.globl	plat_secondary_cold_boot_setup
	.globl	plat_get_my_entrypoint
	.globl	plat_is_my_cpu_primary
	.globl	plat_alif_calc_core_pos
	.globl  plat_my_core_pos
	.globl	plat_crash_console_init
	.globl	plat_crash_console_putc
	.globl	plat_crash_console_flush
	.globl	wfi_loop
	.globl	secondary_cpu_flags

	/* --------------------------------------------------------------------
	 * void plat_secondary_cold_boot_setup (void);
	 * --------------------------------------------------------------------
	 */
func plat_secondary_cold_boot_setup
	mrc p15, 0, r0, c0, c0, 5	/* Read MPIDR to get current cpu core */
	and	r0, r0, #0x3
	sub	r0, r0, #1
	lsl	r0, r0, #2
	ldr	r1, =secondary_cpu_flags
	add	r1, r1, r0
	ldr	r1, [r1 , #0]
	mov	r0, #0xADD		/* Test if the flag 0xADD has been set */
	cmp	r1, r0
	bne	wfi_loop		/* If not go to wfi and powerdown */
	ldr	r9, =sp_min_warm_entrypoint
	mov	pc, r9
endfunc plat_secondary_cold_boot_setup

func wfi_loop
	mrrc    15, 1, r0, r1, cr15
	bic     r0, r0, #0x40 		/* Disable SMP_EN bit in CPUECTLR reg */
	mcrr    15, 1, r0, r1, cr15
wfi_lp:	mov r0,r0
	wfi
	b	wfi_lp
endfunc wfi_loop

	.pushsection .data
	.align 2
secondary_cpu_flags:
	.rept	10
	.word	0
	.endr
	.popsection

func plat_get_my_entrypoint
	/* Cold reset */
	mov	r0, #0
	bx	lr
endfunc plat_get_my_entrypoint

	/* -----------------------------------------------------
	 * unsigned int plat_is_my_cpu_primary (void);
	 *
	 * Find out whether the current CPU is the primary
	 * CPU.
	 * -----------------------------------------------------
	 */
func plat_is_my_cpu_primary
	ldcopr	r0, MPIDR
	ldr	r1, =MPIDR_AFFINITY_MASK
	and	r0, r1
	cmp	r0, #0
	moveq	r0, #1
	movne	r0, #0
	bx	lr
endfunc plat_is_my_cpu_primary

func plat_my_core_pos
	ldcopr	r0, MPIDR
	b	plat_alif_calc_core_pos
endfunc plat_my_core_pos

	/* ---------------------------------------------------------------------
	 * unsigned int plat_alif_calc_core_pos(u_register_t mpidr)
	 *
	 * Function to calculate the core position on Corstone700.
	 *
	 * (ClusterId * MAX_CPUS_PER_CLUSTER * MAX_PE_PER_CPU) +
	 * (CPUId * MAX_PE_PER_CPU) +
	 * ThreadId
	 *
	 * which can be simplified as:
	 *
	 * ((ClusterId * MAX_CPUS_PER_CLUSTER + CPUId) * MAX_PE_PER_CPU)
	 * + ThreadId
	 * ---------------------------------------------------------------------
	 */
func plat_alif_calc_core_pos
	mov	r3, r0

	/* Extract individual affinity fields from MPIDR */
	ubfx	r0, r3, #MPIDR_AFF0_SHIFT, #MPIDR_AFFINITY_BITS
	ubfx	r1, r3, #MPIDR_AFF1_SHIFT, #MPIDR_AFFINITY_BITS
	ubfx	r2, r3, #MPIDR_AFF2_SHIFT, #MPIDR_AFFINITY_BITS

	/* Compute linear position */
	mov	r3, #DEVKIT_E7_MAX_CPUS_PER_CLUSTER
	mla	r1, r2, r3, r1
	mov	r3, #DEVKIT_E7_MAX_PE_PER_CPU
	mla	r0, r1, r3, r0

	bx	lr
endfunc plat_alif_calc_core_pos

	/* ---------------------------------------------
	 * int plat_crash_console_init(void)
	 * Function to initialize the crash console
	 * without a C Runtime to print crash report.
	 * Clobber list : r0 - r3
	 * ---------------------------------------------
	 */
func plat_crash_console_init
	mov 	r0, #0
	bx	lr
endfunc plat_crash_console_init

	/* ---------------------------------------------
	 * int plat_crash_console_putc(int c)
	 * Function to print a character on the crash
	 * console without a C Runtime.
	 * Clobber list : r1 - r2
	 * ---------------------------------------------
	 */
func plat_crash_console_putc
	mov 	r0, #0
	bx	lr
endfunc plat_crash_console_putc

	/* ---------------------------------------------
	 * int plat_crash_console_flush()
	 * Function to force a write of all buffered
	 * data that hasn't been output.
	 * Out : return -1 on error else return 0.
	 * Clobber list : r0
	 * ---------------------------------------------
	 */
func plat_crash_console_flush
	mov 	r0, #0
	bx	lr
endfunc plat_crash_console_flush
